### ISSUE TITLE
Themes are not displayed correctly

### ISSUE THREAD

**Issue by MCGHH** [icedman/vim-textmate#1]
I followed instructions on the README, am I missing something ?
I had trouble to find grammar packages and themes
I copied contents of the folder `/opt/visual-studio-code/resources/app/extensions/`
inside `~/.vim/lua/vim-textmate/extensions/` and set themes corresponding to the output of `txmt_info_themes`

EDIT:  Background and line number color are not set, some themes like `Dark+ (default dark)` doesn't work at all and defaults Monokai colors
```
:lua txmt_info_themes()
themes available:                                                                                                                                                                     
Abyss, Dark+ (default dark), Light+ (default light), Dark (Visual Studio), Light (Visual Studio), High Contrast, Kimbie Dark, Monokai, Monokai Dimmed, Quiet Light, Red, Solarized Dar
k, Solarized Light, Tomorrow Night Blue
```

**Comment by icedman** [comment]
This plugins has some quirks. 
One is that you must set a colorscheme before loading vim-textmate

```
colorscheme tokyonight
luafile ~/Developer/Projects/vim-textmate/vim-textmate.lua
TxmtSetTheme "Monokai"
```

**Comment by MCGHH** [comment]
Well, this plugin is nice.
When I'll have some time, I'll take a look and try to figure out why some themes are discarded.
I thought setting the colorscheme before loading the plugin was a hack until you respond,
but it is the expected behavior.
Thanks.
